spring.application.name=EmployeeAttendanceSystem

server.port=8080

# ======================
# DATABASE CONFIGURATION
# ======================

spring.datasource.url=jdbc:mysql://localhost:3306/employee
spring.datasource.username=root
spring.datasource.password=suhail@94433
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ======================
# JPA CONFIGURATION
# ======================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ======================
# JWT CONFIGURATION
# ======================

jwt.secret=VGhpc0lzQVNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbkFuZFZhbGlkYXRpb24=
jwt.expiration=86400000

# ======================
# SWAGGER
# ======================

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.default-produces-media-type=application/json

# ======================
# LOGGING
# ======================

logging.level.org.springframework.security=DEBUG